theme: jekyll-theme-hacker
<<<<<<< HEAD
title: Welcome to rwhittaker5150's homepage!
description: Feel free to bookmark this to keep an eye on my project updates.
=======
title: Welcome to Travel With Us!
description: This is my capstone project.  Feel free to bookmark this to keep an eye on my project updates.
>>>>>>> refs/heads/master
